<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="sample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="sample.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Update="sample2.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>
